In [20]:
from datetime import timedelta

import numpy as np
import pandas as pd
import xarray as xr

data = 283 + 5 * np.random.randn(5, 3, 4)
times = pd.date_range('2018-01-01', periods=5)
lons = np.linspace(-120, -60, 4)
lats = np.linspace(25, 55, 3)
temp = xr.DataArray(data, coords=[times, lats, lons], dims=['time', 'lat', 'lon'])
temp

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[286.56908718, 279.28562563, 278.70011785, 280.85441752],
        [289.29433567, 277.43622717, 278.36205881, 279.77425966],
        [283.02953864, 285.45087543, 284.75314564, 280.00002132]],

       [[283.64017908, 291.43190976, 284.34124554, 279.95335681],
        [283.85542768, 283.30661223, 278.35262799, 279.23163825],
        [279.46699437, 285.41491188, 284.03646893, 276.49280577]],

       [[284.24527386, 276.7981899 , 285.64423111, 286.37358064],
        [285.95733085, 288.50493676, 286.9476631 , 279.24634975],
        [284.72857196, 282.68710861, 286.47863964, 286.7172255 ]],

       [[280.85236296, 272.79820147, 284.95489471, 287.37604859],
        [282.29551388, 288.29885004, 292.27741093, 278.46334705],
        [278.05250552, 278.91790134, 282.6156894 , 278.74734338]],

       [[288.71018711, 281.57293476, 283.33530941, 284.44665139],
        [278.32122305, 283.1406981 , 281.67571324, 283.11759824],
        [276.33383138, 284.42105797, 288.16244609, 287.47634841]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0

In [7]:
temp.attrs['units'] = 'kelvin'
temp.attrs['standard_name'] = 'air_temperature'

pressure_data = 1000.0 + 5 * np.random.randn(5, 3, 4)
pressure = xr.DataArray(
    pressure_data, coords=[times, lats, lons], dims=['time', 'lat', 'lon']
)
pressure.attrs['units'] = 'hPa'
pressure.attrs['standard_name'] = 'air_pressure'

In [8]:
ds = xr.Dataset(data_vars={'Temperature': temp, 'Pressure': pressure})

<xarray.Dataset>
Dimensions:      (lat: 3, lon: 4, time: 5)
Coordinates:
  * time         (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat          (lat) float64 25.0 40.0 55.0
  * lon          (lon) float64 -120.0 -100.0 -80.0 -60.0
Data variables:
    Temperature  (time, lat, lon) float64 282.6 285.3 278.6 ... 284.8 293.1
    Pressure     (time, lat, lon) float64 990.6 1.003e+03 ... 1.004e+03

In [10]:
indexed_selection = temp[1, :, :]  # Index 1 along axis 0 is the time slice we want...
indexed_selection

<xarray.DataArray (lat: 3, lon: 4)>
array([[280.4035635 , 279.21065213, 281.18369103, 293.21085748],
       [279.99129721, 282.98611588, 284.44827681, 279.07362961],
       [283.00744399, 288.57580011, 291.20932957, 288.53409604]])
Coordinates:
    time     datetime64[ns] 2018-01-02
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [28]:
print(temp.time)
temp.time
#print(temp.lat)
named_selection = temp.sel(time='2018-01-02')
#named_selection

<xarray.DataArray 'time' (time: 5)>
array(['2018-01-01T00:00:00.000000000', '2018-01-02T00:00:00.000000000',
       '2018-01-03T00:00:00.000000000', '2018-01-04T00:00:00.000000000',
       '2018-01-05T00:00:00.000000000'], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05


In [34]:
print(temp.lat)
named_selection2 = temp.sel(lat=25)

<xarray.DataArray 'lat' (lat: 3)>
array([25., 40., 55.])
Coordinates:
  * lat      (lat) float64 25.0 40.0 55.0
